# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://de-badkamer.be
baseurl:
title: "de badkamer: Uw wensen op maat"
email:
author:
description:
port: 4002


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #




# Build settings
markdown: kramdown
permalink: pretty
